config/routes.rb
Saleboard::Application.routes.draw do

  resources :locations

  devise_for :users

  resources :products do 
    resources :comments
  end

  resources :users do 
    resources :products
  end

  root to: 'products#index' 

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :product_id
  validates :user, presence: true
  belongs_to :user
  belongs_to :product
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :address, :latitude, :longitude
  geocoded_by :address
  after_validation :geocode
end

app/models/product.rb
  class Product < ActiveRecord::Base
  attr_accessible :description, :price, :image, :address, :latitude, :longitude
  validates :description, :price, presence: true
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
  #validates :user, presence: true

  has_many :comments
  belongs_to :user

  has_attached_file :image, 
  :styles => {
    :thumb => "100x100#",
    :small => "140x140>",
    :medium => "200x200>" }
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible  :email, :password, :password_confirmation, :remember_me, :image, :image_url, 
  :address, :longitude, :latitude
  # attr_accessible :title, :body

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

  has_many :comments
  has_many :products

  has_attached_file :image

  geocoded_by :current_sign_in_ip,
  :latitude => :latitude, :longitude => :longitude, :address => :address
  after_validation :geocode


  def display_name
    if provider=='twitter'
      name 
    else
      " #{email}"
    end
  end

  def email_required?
    uid.blank?
  end

  def password_required?
    uid.blank? && new_record?
  end
private

  def fetch_address
    if address.blank?
      # Geocode based on current_sign_in_ip
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		product = Product.find(params[:product_id])
		@comment = product.comments.build(params[:comment])
		@comment.user = current_user

		if @comment.save
			 # Tell the UserMailer to send a welcome Email after save
        MyMailer.comment_email(product.user, @comment).deliver
        #MyMailer.welcome_email(product.user.all).deliver
			redirect_to products_path
		else
			render :new
		end
	end

	def destroy
		@comment = Product.find(params[:id])
		@product.destroy
		redirect_to products_path

	end

		def edit 
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
			if @product.update_attributes params[:product]
				redirect_to products_path
			else
				render :edit	
			end
	end


	def new
		@comment = Comment.new
	end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
  end

  def show
    @location = Location.find(params[:id])
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(params[:location])
    if @location.save
      redirect_to @location, :notice => "Successfully created location."
    else
      render :action => 'new'
    end
  end

  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
    if @location.update_attributes(params[:location])
      redirect_to @location, :notice  => "Successfully updated location."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    redirect_to locations_url, :notice => "Successfully destroyed location."
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

skip_before_filter :authenticate_user!, only: [:index]
	def index
		user_id = params[:user_id]
		if user_id
			@products = Product.where(user_id: user_id)    	
		else	
			@products  = Product.includes(:comments)
		end

		if params[:search].present?
			@search = params[:search]
    	@products = @products.near(params[:search], params[:distance], :order => :distance)
  	end
		
		if params[:description].present?
			#@products = @products.includes(:comments).where(description: params[:description])
			@products = @products.where("description LIKE ?" , "%#{params[:description]}%")
		end
	end



	def edit 
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
			if @product.update_attributes params[:product]
				redirect_to products_path
			else
				render :edit
			end
	end


	def new
		@product = Product.new
	end

	def create 
		@product = current_user.products.build(params[:product])
		if @product.save
			redirect_to products_path
		else
			render :new
		end
	end

	def show
    @product = Product.find(params[:id])
  end

  def destroy
		@product = Product.find(params[:id])
		@product.destroy
		redirect_to products_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def update
      u = User.find(params[:id])
      u.address = params[:user][:address]
      u.save!
      redirect_to products_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class='well well-small span4'>
    <p class ='lead '>
        <%=comment.body%>
    </p>
   <em>   
   <%= comment.user.display_name%> posted this comment <%= time_ago_in_words(comment.created_at, include_seconds = false) %> ago
    </em>
</div>

app/views/comments/_form.html.erb
<div class=' span4'>
<%= form_for [product, comment] do |f| %>
	<%= f.text_field :body, placeholder: 'Comment...'%>
  <div>
	<%=f.submit :class => 'btn btn-primary'%>
</div>
<% end %>
</div>

app/views/comments/edit.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>nearzbuy</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

<link href="//netdna.bootstrapcdn.com/bootswatch/2.3.1/amelia/bootstrap.min.css" rel="stylesheet">
<script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js"></script>

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-responsive.min.css" rel="stylesheet">

</head>
<body>


<div class="navbar navbar">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "nearzbuy", products_path, class: 'brand' %>
 
      <ul class ="nav pull-right">
             <%= render 'products/search' %>
        <% if user_signed_in? %>
    
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">

             <%=current_user.display_name%> <b>v</b>
            
          </a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="dlabel">
             <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
             
          </ul>
      

     
        
      <% else %>
         <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <li><%= link_to "Sign in with Twitter", 
              user_omniauth_authorize_path(:twitter) %> </li>
      <%end%>	
    </li>
  </ul>

      

      </div>
  </div>
</div>

<div class="container">
          <%= yield %>

</div>





</body>
</html>

app/views/locations/_form.html.erb
<%= form_for @location do |f| %>

  <p>
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </p>
  <p>
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/locations/edit.html.erb
<%= render 'form' %>

<p>
  <%= link_to "Show", @location %> |
  <%= link_to "View All", locations_path %>
</p>

app/views/locations/index.html.erb
<table>
  <tr>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longitude</th>
  </tr>
  <% for location in @locations %>
    <tr>
      <td><%= location.address %></td>
      <td><%= location.latitude %></td>
      <td><%= location.longitude %></td>
      <td><%= link_to "Show", location %></td>
      <td><%= link_to "Edit", edit_location_path(location) %></td>
      <td><%= link_to "Destroy", location, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Location", new_location_path %></p>

app/views/locations/new.html.erb
<%= render 'form' %>

<p><%= link_to "Back to List", locations_path %></p>

app/views/locations/show.html.erb
<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>
<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>
<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<p>
  <%= link_to "Edit", edit_location_path(@location) %> |
  <%= link_to "Destroy", @location, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", locations_path %>
</p>

app/views/products/_form.html.erb
<h1> New Product </h1>

<% if @product.errors.any? %>
  <div class='alert alert-error'>
    <strong> Error! </strong> Your Product cannot be saved:
    
    <ul>
      <%@product.errors.full_messages.each do |message|%>
        <li><%=message%></li>
      <% end %>
    </ul>
  </div>
<%end%>

<%= form_for @product, :html => {multipart: true} do |f| %>

  <div>
    <%= f.file_field :image %>
  </div>

 <div>
    <%= f.label :description %>
    <%= f.text_area :description, rows: 3%>
  </div>


  <div>
    <%= f.label :price %>
      <div class="input-prepend"> 
        <span class="add-on">$</span>
        <%= f.text_field :price, :class => 'span2 input-prepend' %>
      </div>
  </div>

 

  <p>
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </p>



  <div>
    <%=f.submit "Save Product", class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/products/_search.html.erb
<%= form_tag products_path, method: :get, :class=> 'navbar-search form-inline navbar-text' do %>
  <%=label_tag :description, "Find " %>
  <%= text_field_tag :description, params[:description], :class => "search-query input-medium",  
  placeholder:"Product" %>
  <%= label_tag :search, " within "%>
  <%= select_tag :distance, options_for_select([5, 10, 25, 50, 100]), :class => "input-small"%> miles of
  <%= text_field_tag :search, params[:search], :class => "search-query input-small", placeholder:"Postal Code"%> 
  
  <%= submit_tag "search", :class => 'btn btn-small'%>

<% end %>

app/views/products/edit.html.erb
<%= render 'form' %>

app/views/products/index.html.erb
<div class="page-header">
  <h1>Near

    <% if user_signed_in? %>	
    
    	<small>
    		<% if current_user.address.present? %>
	    		<%=current_user.address%>
    		<% else %>
	    		<%= render "users/address", user: current_user %>
    		<% end %>

    	</small>
    </h1>
        <%= link_to "Sell Something", new_product_path, :class=>'btn btn-primary'%></li>
      <%end%>	

    
</div>

	

<% @products.each_with_index do |p, i| %>
<div class= 'media well'> 
				<%= image_tag p.image.url(:medium), :class=>'img-polaroid	media-object pull-left'%> 
					
			<div class ="media-body">	
				 <p class = 'lead'>
				 		<%= p.description %>
					</p>
					 <p class = 'lead'>	 
				 		<strong>
				 				$<%= p.price%>
				 		
				 		</strong>
				 	</p>

					<p class ="muted"> 
				 		<% if @search %>
				 			<%=number_with_precision(p.distance_to(@search), :precision => 2)%> miles from <%=@search%>
				 			<%else%>
				 			<% if user_signed_in? %>
							<%=number_with_precision(p.distance_to(current_user.address), :precision => 2)%> miles from You
							<%end%>
		 				<%end%> 
		 			</p>
				
					<p>
					<em>
				 		posted <%= time_ago_in_words(p.created_at,
				 		include_seconds = false)%> ago
				 	</em>
		 			</p>
		 			<p>
		 				<%= link_to "More", product_path(p.id), :class => 'btn btn-small'  %>
						<% if current_user == p.user%>
							<%= link_to 'Edit', edit_product_path(p), :class => 'btn btn-small' %>
							<%= link_to 'Delete', p, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-small'  %> 
						<%end%>
					</p>
				</div>
			</div>
		
	
	<%end%>

app/views/products/new.html.erb
<%= render 'form' %>

app/views/products/show.html.erb
<div class = "media well clearfix">
   <%= image_tag @product.image.url(:medium), :class => "img-polaroid media-object pull-left"%>  
  <div class = "media-body"> 
    <p class = 'lead'>
      <%= @product.description %>
      $<%= @product.price %>
    <p>
  </div>
</div>


 
 <%= render @product.comments %>


 <%= render 'comments/form', comment: @product.comments.build, product: @product %>

app/views/users/_address.html.erb
<%= form_for current_user do |f|%>
  <%= f.text_field :address, placeholder: 'Postal Code'%>
  <%=f.submit%>
<% end %>

app/views/users/_location.html.erb
<%= form_for @users, :html => {multipart: true} do |f| %>
 
  <p>
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </p>



  <div>
    <%=f.submit "Update Location", class: 'btn btn-primary' %>
  </div>

<% end %>